language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
# command to install dependencies, 
install:
    - pip install -vr requirements.txt||true
# command to run tests, e.g. python setup.py test
script:
  - echo $TRAVIS_PYTHON_VERSION
  - cd .. && supybot-test WorldTime
notifications:
    email: false
    irc:
      channels:
        - "irc.efnet.net#supybot"
    webhooks:
	- http://n.tkte.ch/h/3423/NoKkj8qlifpaTelhx-u9Qvdl
matrix:
    fast_finish: true

